apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl
spec:
  schedule: "*/5 * * * *"  # Executa a cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl
            image: etl-container:latest  # Use a imagem local
            imagePullPolicy: Never  # Usa a imagem local, se disponível
          restartPolicy: OnFailure
