import pandas as pd
import numpy as np

# Importação do DataFrame
df = pd.read_csv("/home/ryan/trabBD3/BrFlights2.csv")

# Normalização do Código de Voo da empresa GOL
df_numerico_Voos = df['Voos'].str.replace(r'\D', '', regex=True)  # Retira tudo que não é número
df_string_Voos = np.where(df['Voos'].str.contains("GLO"), "GOL-", df['Voos'])  # Normaliza string para GOL-

# Atualiza a coluna 'Voos' com a string e parte numérica
df['Voos'] = np.where(df['Voos'].str.contains("GLO"), df_string_Voos + df_numerico_Voos, df['Voos'])

# Modifica o que for Regional para Nacionaç
df["Codigo.Tipo.Linha"]= np.where(df["Codigo.Tipo.Linha"].str.contains("Regional"),"Nacional", df["Codigo.Tipo.Linha"])

#Padroniza tudo para - 
df["Aeroporto.Destino"] = df["Aeroporto.Destino"].str.replace("/", "-", regex=True)

#Conserta o nome dacidade de Abu Dabhi
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Abu Dhabi"), "",df["Cidade.Origem"] )

#Padroniza toda as cidades que não tinham estado de origem ou destino
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Abu Dhabi International"), "AUH",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Addis Ababa"), "ADD",df["Estado.Origem"])
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Amsterdam"), "NH",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Aruba"), "AW",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Assunção"), "ASU",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Atlanta"), "GA",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Barcelona"), "CT",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Bogotá"), "DC",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Bridgetown"), "BB",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Buenos Aires"), "CABA",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Buenos Aires"), "CABA",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Cabo Verde"), "ST",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Caiena"), "GF",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Cancún"), "QR",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Caracas"), "LG",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Casablanca"), "CS",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Cheddi Jagan "), "DM",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Chicago"), "IL",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Cidade Del Este"), "AP",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Córdoba"), "CB",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Curaçao"), "CW",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Detroit"), "MI",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Doha"), "DOH",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Dubai International"), "DXB",df["Estado.Origem"] )
df["Cidade.Origem"]= np.where(df["Cidade.Origem"].str.contains("Fort Lauderdale"), "FL",df["Estado.Origem"] )
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Zurique"), "ZH", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Zandery"), "PM", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Washington/Dulles Intl"), "VA", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Viru Viru"), "SC", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Toronto"), "ON", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Santiago Do Chile"), "RM", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Rosario"), "SF", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Roma"), "LAZ", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Quito"), "PI", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Punta Cana"), "LA", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Porto"), "POR", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Paris"), "IDF", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Panama"), "PN", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Orlando"), "FL", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Newark / Intl Nj"), "NJ", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("New York"), "NY", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Munchen"), "BY", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Montevideu"), "MVD", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Milao"), "LOM", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Miami"), "FL", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Mendoza"), "MZA", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Maldonado-Uruguai"), "MA", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Madrid"), "MD", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Luanda"), "LUA", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Londres"), "ENG", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Lome"), "MR", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Lisboa"), "LIS", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Lima"), "LMA", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Johannesburg"), "GP", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Istanbul/Ataturk"), "IST", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Ilha Do Sal"), "SAL", df["Estado.Origem"])
df["Cidade.Origem"] = np.where(df["Cidade.Origem"].srt.contains("Frankfurt"), "HE", df["Estado.Origem"])



df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Abu Dhabi International"), "AUH",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Addis Ababa"), "ADD",df["Estado.Destino"])
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Amsterdam"), "NH",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Aruba"), "AW",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Assunção"), "ASU",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Atlanta"), "GA",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Barcelona"), "CT",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Bogotá"), "DC",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Bridgetown"), "BB",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Buenos Aires"), "CABA",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Buenos Aires"), "CABA",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Cabo Verde"), "ST",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Caiena"), "GF",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Cancún"), "QR",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Caracas"), "LG",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Casablanca"), "CS",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Cheddi Jagan "), "DM",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Chicago"), "IL",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Cidade Del Este"), "AP",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Córdoba"), "CB",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Curaçao"), "CW",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Detroit"), "MI",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Doha"), "DOH",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Dubai International"), "DXB",df["Estado.Destino"] )
df["Cidade.Destino"]= np.where(df["Cidade.Destino"].str.contains("Fort Lauderdale"), "FL",df["Estado.Destino"] )
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Zurique"), "ZH", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Zandery"), "PM", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Washington/Dulles Intl"), "VA", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Viru Viru"), "SC", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Toronto"), "ON", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Santiago Do Chile"), "RM", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Rosario"), "SF", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Roma"), "LAZ", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Quito"), "PI", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Punta Cana"), "LA", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Porto"), "POR", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Paris"), "IDF", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Panama"), "PN", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Orlando"), "FL", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Newark / Intl Nj"), "NJ", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("New York"), "NY", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Munchen"), "BY", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Montevideu"), "MVD", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Milao"), "LOM", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Miami"), "FL", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Mendoza"), "MZA", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Maldonado-Uruguai"), "MA", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Madrid"), "MD", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Luanda"), "LUA", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Londres"), "ENG", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Lome"), "MR", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Lisboa"), "LIS", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Lima"), "LMA", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Johannesburg"), "GP", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Istanbul/Ataturk"), "IST", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Ilha Do Sal"), "SAL", df["Estado.Destino"])
df["Cidade.Destino"] = np.where(df["Cidade.Destino"].srt.contains("Frankfurt"), "HE", df["Estado.Destino"])

